# Generated by Django 5.1.2 on 2025-10-30 23:11

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha_inicio'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_fin',
            field=models.DateTimeField(default=timezone.now, help_text='Fecha y hora de fin de la cita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_inicio',
            field=models.DateTimeField(default=timezone.now, help_text='Fecha y hora de inicio de la cita'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='hora',
        ),
    ]
