# Generated by Django 5.1.2 on 2025-11-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_cita_options_alter_cita_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
