# Generated by Django 5.1.2 on 2025-10-03 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('teams', '0002_team_slug'),
        ('tiendas', '0002_tienda_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tiendas.tienda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='teams.team'),
        ),
        migrations.AddField(
            model_name='stock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='productos.producto'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='tiendas.tienda'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('producto', 'sucursal')},
        ),
    ]
