# Generated by Django 5.1.2 on 2025-12-22 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_stock_options_producto_team_stock_producto'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenes',
            field=models.JSONField(blank=True, default=list, help_text='URLs de imágenes del producto'),
        ),
    ]
