# Generated by Django 5.1.2 on 2025-12-22 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagenes_producto_team_stock_producto'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='producto',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='productos.producto'),
            preserve_default=False,
        ),
    ]
