# Generated by Django 5.1.2 on 2026-05-22 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integraciones', '0003_googlesheetintegration'),
        ('leads', '0002_lead_usuario_asignado'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.TextField(help_text='Texto de la plantilla. Puede incluir variables como {{nombre}}')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviando', 'Enviando'), ('completado', 'Completado'), ('error', 'Error')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='teams.team')),
                ('whatsapp_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integraciones.whatsappinstance')),
                ('plantilla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='campaigns.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='CampanaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campana_leads', to='campaigns.campana')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campana_leads', to='leads.lead')),
            ],
            options={
                'unique_together': {('campana', 'lead')},
            },
        ),
    ]
