# Generated by Django 5.1.2 on 2026-04-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giro', models.CharField(choices=[('tecnologia', 'Tecnología'), ('retail', 'Retail'), ('finanzas', 'Finanzas'), ('salud', 'Salud'), ('educacion', 'Educación')], max_length=50)),
                ('cliente', models.CharField(max_length=255)),
                ('campana', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('video', 'Video'), ('imagen', 'Imagen'), ('banner', 'Banner'), ('texto', 'Texto')], max_length=50)),
                ('duracion', models.IntegerField(help_text='Duración en días')),
                ('impactos', models.IntegerField()),
                ('engagement', models.FloatField(help_text='Porcentaje de engagement')),
                ('roi', models.FloatField(help_text='Retorno sobre inversión')),
                ('imagen', models.ImageField(upload_to='portafolio/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='teams.team')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
    ]
