# Generated by Django 5.1.2 on 2026-04-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
