# Generated by Django 5.1.2 on 2026-04-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_portafolio_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='campana',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='engagement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='formato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='giro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='imagen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='impactos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='roi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
