# Generated by Django 5.1.2 on 2026-04-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_portafolio_disponible_alter_portafolio_campana_and_more'),
        ('portafolio', '0003_alter_portafolio_campana_alter_portafolio_cliente_and_more'),
    ]

    operations = [
    ]
