# Generated by Django 5.1.2 on 2025-07-30 06:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('web', 'Sitio Web'), ('otro', 'Otro')], max_length=20)),
                ('plataforma_id', models.CharField(help_text='ID del usuario en la plataforma', max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="El teléfono debe estar en formato: '+999999999'. Hasta 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('en_seguimiento', 'En Seguimiento'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('fuente', models.CharField(choices=[('comentario', 'Comentario'), ('mensaje_directo', 'Mensaje Directo'), ('mencion', 'Mención'), ('formulario', 'Formulario'), ('referido', 'Referido'), ('llamada', 'Llamada'), ('otro', 'Otro')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ultima_interaccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('probabilidad_conversion', models.IntegerField(default=0, help_text='Porcentaje de 0 a 100')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_asignados', to='teams.team')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='ActividadLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('asignacion', 'Asignación'), ('cambio_estado', 'Cambio de Estado'), ('nota', 'Nota Agregada'), ('mensaje', 'Mensaje Enviado'), ('llamada', 'Llamada'), ('reunion', 'Reunión')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Actividad de Lead',
                'verbose_name_plural': 'Actividades de Lead',
                'db_table': 'actividades_lead',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['plataforma', 'plataforma_id'], name='leads_platafo_6fa11a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['estado'], name='leads_estado_b3716d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['fecha_creacion'], name='leads_fecha_c_20a517_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['asignado_a'], name='leads_asignad_178bdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('plataforma', 'plataforma_id')},
        ),
    ]
