# Generated by Django 5.1.2 on 2026-05-16 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=255)),
                ('instance_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='disconnected', max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instances', to='teams.team')),
            ],
        ),
    ]
