# Generated by Django 5.1.2 on 2026-05-16 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0002_whatsappinstance'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=255)),
                ('sheet_name', models.CharField(default='Sheet1', max_length=100)),
                ('entidad', models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], max_length=20)),
                ('mapping', models.JSONField(default=dict, help_text='Mapeo de campos del sistema a columnas del Sheet')),
                ('identificadores', models.JSONField(default=list, help_text='Campos usados para verificar si el registro ya existe')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='googlesheet_integrations', to='teams.team')),
            ],
        ),
    ]
