# Generated by Django 5.1.2 on 2025-11-28 22:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='archivos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'xlsx', 'csv'])])),
                ('tipo_archivo', models.CharField(choices=[('contrato', 'Contrato'), ('documento', 'Documento'), ('imagen', 'Imagen'), ('otro', 'Otro')], default='documento', max_length=20)),
                ('tamano', models.BigIntegerField(help_text='Tamaño en bytes')),
                ('hash_sha256', models.CharField(blank=True, help_text='Hash SHA-256 del archivo para verificación de integridad', max_length=64)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('es_privado', models.BooleanField(default=True)),
                ('requiere_autenticacion', models.BooleanField(default=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='teams.team')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='AccesoArchivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(choices=[('visualizacion', 'Visualización'), ('descarga', 'Descarga'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='archivos.archivo')),
            ],
            options={
                'verbose_name': 'Acceso a Archivo',
                'verbose_name_plural': 'Accesos a Archivos',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['team', '-fecha_subida'], name='archivos_ar_team_id_bd5cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['hash_sha256'], name='archivos_ar_hash_sh_f0db34_idx'),
        ),
        migrations.AddIndex(
            model_name='accesoarchivo',
            index=models.Index(fields=['archivo', '-fecha_acceso'], name='archivos_ac_archivo_c2b51e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesoarchivo',
            index=models.Index(fields=['usuario', '-fecha_acceso'], name='archivos_ac_usuario_403eed_idx'),
        ),
    ]
