# Generated by Django 5.1.2 on 2026-02-01 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg', 'png', 'xlsx', 'csv', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tamano',
            field=models.BigIntegerField(blank=True, help_text='Tamaño en bytes', null=True),
        ),
    ]
