# Generated by Django 5.1.2 on 2026-03-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_archivo_archivo_alter_archivo_tamano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='es_privado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='requiere_autenticacion',
            field=models.BooleanField(default=False),
        ),
    ]
