# Generated by Django 5.1.2 on 2026-04-22 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0003_alter_archivo_es_privado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivo_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='archivo_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
