# Generated by Django 5.1.2 on 2026-04-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0004_remove_archivo_archivo_archivo_archivo_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('audio', 'Audio'), ('documento', 'Documento'), ('otro', 'Otro')], default='documento', max_length=20),
        ),
    ]
