# Generated by Django 5.1.2 on 2025-12-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='url_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
