# Generated by Django 5.1.2 on 2026-04-16 05:48

import django.db.models.deletion
import utils.generate_radom_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicio_url_img'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Booleano')], max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('personalizado_id', models.CharField(default=utils.generate_radom_code.generar_codigo, editable=False, max_length=6, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='teams.team')),
            ],
            options={
                'verbose_name': 'Campo Personalizado',
                'verbose_name_plural': 'Campos Personalizados',
                'db_table': 'campos_personalizados',
            },
        ),
        migrations.CreateModel(
            name='ServicioCampoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='servicios.campopersonalizado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_valores', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Valor de Campo',
                'verbose_name_plural': 'Valores de Campos',
                'db_table': 'servicio_campo_valores',
                'unique_together': {('servicio', 'campo')},
            },
        ),
    ]
