# Generated by Django 5.1.2 on 2026-04-17 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_campopersonalizado_serviciocampovalor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciocampovalor',
            name='campo',
        ),
        migrations.AlterUniqueTogether(
            name='serviciocampovalor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='serviciocampovalor',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='CampoPersonalizado',
        ),
        migrations.DeleteModel(
            name='ServicioCampoValor',
        ),
    ]
