# Generated by Django 5.1.2 on 2026-04-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad', models.CharField(choices=[('lead', 'Lead'), ('servicio', 'Servicio'), ('producto', 'Producto'), ('contacto', 'Contacto'), ('orden', 'Orden')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.SlugField(help_text="Clave interna sin espacios, ej: 'fecha_cierre'", max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('decimal', 'Decimal'), ('fecha', 'Fecha'), ('datetime', 'Fecha y hora'), ('booleano', 'Booleano'), ('seleccion', 'Selección (opciones)'), ('url', 'URL'), ('email', 'Email'), ('telefono', 'Teléfono')], default='texto', max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='teams.team')),
            ],
            options={
                'verbose_name': 'Campo personalizado',
                'verbose_name_plural': 'Campos personalizados',
                'db_table': 'campos',
                'ordering': ['entidad', 'orden', 'nombre'],
                'unique_together': {('team', 'entidad', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='CampoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('valor', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='campos.campo')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Valor de campo',
                'verbose_name_plural': 'Valores de campos',
                'db_table': 'campos_valores',
                'unique_together': {('campo', 'content_type', 'object_id')},
            },
        ),
    ]
