# Generated by Django 5.1.2 on 2025-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('usuario', 'Usuario'), ('invitado', 'Invitado'), ('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('empleado', 'Empleado'), ('paciente', 'Paciente'), ('miembro', 'Miembro'), ('arrendador', 'Arrendador'), ('otro', 'Otro')], max_length=20),
        ),
    ]
