# Generated by Django 5.1.2 on 2025-11-14 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REGISTRO', 'Registro de cuenta'), ('MENSAJE', 'Mensaje enviado'), ('CITA_AGENDADA', 'Cita agendada'), ('CITA_COMPLETADA', 'Cita completada'), ('CITA_CANCELADA', 'Cita cancelada'), ('DOCUMENTO_SUBIDO', 'Documento subido'), ('PAGO_REALIZADO', 'Pago realizado'), ('RECORDATORIO_ENVIADO', 'Recordatorio enviado'), ('PERFIL_ACTUALIZADO', 'Perfil actualizado'), ('INICIO_SESION', 'Inicio de sesión')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('IDENTIFICACION', 'Identificación oficial'), ('COMPROBANTE_DOMICILIO', 'Comprobante de domicilio'), ('ESTUDIO_MEDICO', 'Estudio médico'), ('RECETA', 'Receta'), ('CONSENTIMIENTO', 'Consentimiento informado'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('archivo', models.FileField(upload_to='documentos_usuarios/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
