# Generated by Django 5.1.2 on 2025-11-14 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_actividadusuario_documentousuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadusuario',
            options={'ordering': ['-fecha_actividad'], 'verbose_name': 'Actividad de Usuario', 'verbose_name_plural': 'Actividades de Usuario'},
        ),
        migrations.AlterModelOptions(
            name='documentousuario',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Documento de Usuario', 'verbose_name_plural': 'Documentos de Usuario'},
        ),
        migrations.RemoveField(
            model_name='actividadusuario',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='actividadusuario',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='actividadusuario',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='documentousuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='documentousuario',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='documentousuario',
            name='subido_por',
        ),
        migrations.RemoveField(
            model_name='documentousuario',
            name='tipo',
        ),
        migrations.AddField(
            model_name='actividadusuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadusuario',
            name='fecha_actividad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actividadusuario',
            name='tipo_actividad',
            field=models.CharField(choices=[('DOCUMENTO_SUBIDO', 'Documento Subido'), ('DOCUMENTO_ELIMINADO', 'Documento Eliminado'), ('CITA_AGENDADA', 'Cita Agendada'), ('CITA_CANCELADA', 'Cita Cancelada'), ('NOTA_AGREGADA', 'Nota Agregada'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='documentousuario',
            name='tipo_documento',
            field=models.CharField(choices=[('IDENTIFICACION', 'Identificación'), ('HISTORIA_CLINICA', 'Historia Clínica'), ('RADIOGRAFIA', 'Radiografía'), ('LABORATORIO', 'Laboratorio'), ('RECETA', 'Receta'), ('CONSENTIMIENTO', 'Consentimiento'), ('OTRO', 'Otro')], default='OTRO', max_length=50),
        ),
    ]
