# Generated by Django 5.1.2 on 2026-06-16 06:03

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_username_alter_usuario_nombre_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='features_config',
            field=models.JSONField(blank=True, default=apps.usuarios.models.default_features),
        ),
    ]
