# Generated by Django 5.1.2 on 2025-09-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('type', models.CharField(choices=[('TEXT', 'Texto'), ('NUMBER', 'Número'), ('DATE', 'Fecha'), ('BOOLEAN', 'Booleano'), ('MULTIPLE_CHOICE', 'Opción múltiple'), ('EMAIL', 'Email'), ('PHONE', 'Teléfono')], max_length=20)),
                ('required_format', models.CharField(blank=True, max_length=50, null=True)),
                ('options', models.JSONField(blank=True, help_text='Solo para multiple choice: [{key, label}]', null=True)),
                ('auto_extract', models.BooleanField(default=False)),
                ('fuzzy_aliases', models.JSONField(blank=True, help_text='Lista de sinónimos o alias', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('START', 'Inicio'), ('END', 'Fin'), ('QUESTION', 'Pregunta'), ('ACTION', 'Acción'), ('WEBHOOK', 'Webhook'), ('DELAY', 'Delay'), ('SCRIPT', 'Script')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('message_template', models.TextField(blank=True, help_text='Texto con variables {{entity}}')),
                ('collect_entity_mode', models.CharField(choices=[('REQUIRED', 'Requerido'), ('OPTIONAL', 'Opcional'), ('NONE', 'Ninguno')], default='NONE', max_length=20)),
                ('position', models.JSONField(default=dict, help_text='Coordenadas {x, y}')),
                ('ui_settings', models.JSONField(blank=True, null=True)),
                ('collect_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.entity')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flows.flow')),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('condition', models.JSONField(blank=True, help_text='Expresión JSONLogic o DSL', null=True)),
                ('order', models.IntegerField(default=0)),
                ('temporary_hide_on_message', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='flows.node')),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_paths', to='flows.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='default_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flows.path'),
        ),
    ]
