# Generated by Django 5.1.2 on 2025-09-17 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flow',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='options',
            field=models.JSONField(blank=True, help_text="Solo para multiple choice: [{ 'key': str, 'label': str, 'keywords': [str] }]", null=True),
        ),
    ]
