# Generated by Django 5.1.2 on 2025-09-17 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0002_entity_team_flow_team_alter_entity_options'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('slug', 'team')},
        ),
        migrations.CreateModel(
            name='EntityValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(help_text='ID único del remitente (usuario/lead)', max_length=150)),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='flows.entity')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_values', to='teams.team')),
            ],
            options={
                'unique_together': {('entity', 'team', 'sender_id')},
            },
        ),
    ]
