# Generated by Django 5.1.2 on 2025-09-26 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0002_initial'),
        ('flows', '0003_alter_entity_slug_alter_entity_unique_together_and_more'),
        ('leads', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='slug',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='flow',
            name='webhook_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='Token único para seguridad del webhook', null=True),
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('FINISHED', 'Finalizado')], default='ACTIVE', max_length=20)),
                ('context', models.JSONField(default=dict, help_text='Contexto y variables de la sesión')),
                ('platform', models.CharField(blank=True, help_text='Plataforma de origen (whatsapp, telegram, etc)', max_length=50)),
                ('platform_data', models.JSONField(blank=True, help_text='Datos específicos de la plataforma', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to='conversaciones.conversacion')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flows.node')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flows.flow')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_sessions', to='leads.lead')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='teams.team')),
            ],
            options={
                'unique_together': {('sender_id', 'flow', 'team')},
            },
        ),
    ]
