# Generated by Django 5.1.2 on 2025-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0004_flow_slug_flow_webhook_token_conversationsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
