# Generated by Django 5.1.2 on 2026-06-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='max_users',
            field=models.PositiveIntegerField(default=10, help_text='Número máximo de usuarios que pueden pertenecer a este equipo'),
        ),
    ]
