# Generated by Django 5.1.2 on 2025-11-28 22:35

import apps.contratos.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_team_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('documento_original', models.FileField(upload_to='contratos/originales/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('documento_firmado', models.FileField(blank=True, help_text='Documento con todas las firmas aplicadas', null=True, upload_to='contratos/firmados/%Y/%m/%d/')),
                ('hash_documento_original', models.CharField(help_text='Hash SHA-256 del documento original', max_length=64)),
                ('hash_documento_firmado', models.CharField(blank=True, help_text='Hash SHA-256 del documento firmado', max_length=64, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activo', 'Activo - Esperando Firmas'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='borrador', max_length=20)),
                ('token_formulario', models.CharField(default=apps.contratos.models.generar_token_unico, help_text='Token para acceder al formulario de datos', max_length=32, unique=True)),
                ('token_visualizacion', models.CharField(default=apps.contratos.models.generar_token_unico, help_text='Token para visualizar y firmar el contrato', max_length=32, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('requiere_autenticacion_doble', models.BooleanField(default=False, help_text='Requiere código de verificación por email')),
                ('ip_permitidas', models.TextField(blank=True, help_text='IPs permitidas separadas por comas (vacío = todas)')),
                ('limite_intentos_firma', models.IntegerField(default=3)),
                ('email_notificacion', models.EmailField(blank=True, help_text='Email para recibir notificaciones de firmas', max_length=254)),
                ('notificar_cada_firma', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_creados', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='teams.team')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CampoContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_campo', models.CharField(help_text="Nombre identificador del campo (ej: 'nombre_firmante')", max_length=100)),
                ('etiqueta', models.CharField(help_text='Etiqueta visible para el usuario', max_length=200)),
                ('tipo_campo', models.CharField(choices=[('texto', 'Texto'), ('fecha', 'Fecha'), ('dni', 'DNI/Identificación'), ('email', 'Email'), ('telefono', 'Teléfono'), ('firma', 'Firma Digital'), ('iniciales', 'Iniciales'), ('checkbox', 'Checkbox')], max_length=20)),
                ('pagina', models.IntegerField(help_text='Número de página donde se coloca el campo')),
                ('posicion_x', models.FloatField(help_text='Posición X en el PDF (porcentaje)')),
                ('posicion_y', models.FloatField(help_text='Posición Y en el PDF (porcentaje)')),
                ('ancho', models.FloatField(help_text='Ancho del campo (porcentaje)')),
                ('alto', models.FloatField(help_text='Alto del campo (porcentaje)')),
                ('valor', models.TextField(blank=True, help_text='Valor del campo (texto, fecha, etc.)')),
                ('firma_imagen', models.ImageField(blank=True, help_text='Imagen de la firma dibujada', null=True, upload_to='contratos/firmas/%Y/%m/%d/')),
                ('firma_hash', models.CharField(blank=True, help_text='Hash de la firma para verificación', max_length=64)),
                ('firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('ip_firma', models.GenericIPAddressField(blank=True, null=True)),
                ('requerido', models.BooleanField(default=True)),
                ('validacion_regex', models.CharField(blank=True, help_text='Regex para validar el campo', max_length=200)),
                ('mensaje_ayuda', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el formulario')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Campo de Contrato',
                'verbose_name_plural': 'Campos de Contrato',
                'ordering': ['contrato', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='FirmanteContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('dni', models.CharField(blank=True, help_text='DNI/Pasaporte/Identificación', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('token_acceso', models.CharField(default=apps.contratos.models.generar_token_unico, max_length=32, unique=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6)),
                ('codigo_verificacion_expira', models.DateTimeField(blank=True, null=True)),
                ('intentos_verificacion', models.IntegerField(default=0)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('acepta_terminos', models.BooleanField(default=False)),
                ('fecha_aceptacion_terminos', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_invitacion_enviada', models.DateTimeField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmantes', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Firmante',
                'verbose_name_plural': 'Firmantes',
                'ordering': ['contrato', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoFirma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hash_documento', models.CharField(help_text='Hash del documento en el momento de la firma', max_length=64)),
                ('hash_firma', models.CharField(help_text='Hash de la firma aplicada', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('certificado_json', models.JSONField(help_text='Certificado completo en formato JSON')),
                ('hash_certificado', models.CharField(help_text='Hash único del certificado para verificación', max_length=64, unique=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='contratos.contrato')),
                ('firmante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='contratos.firmantecontrato')),
            ],
            options={
                'verbose_name': 'Certificado de Firma',
                'verbose_name_plural': 'Certificados de Firma',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContrato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('activacion', 'Activación'), ('firma', 'Firma'), ('visualizacion', 'Visualización'), ('descarga', 'Descarga'), ('cancelacion', 'Cancelación'), ('completado', 'Completado'), ('envio_email', 'Envío de Email'), ('verificacion', 'Verificación de Código')], max_length=20)),
                ('descripcion', models.TextField()),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contratos.contrato')),
                ('firmante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.firmantecontrato')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Contrato',
                'verbose_name_plural': 'Historial de Contratos',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['team', '-fecha_creacion'], name='contratos_c_team_id_670b14_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['estado'], name='contratos_c_estado_608720_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['token_formulario'], name='contratos_c_token_f_1b2702_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['token_visualizacion'], name='contratos_c_token_v_f86a26_idx'),
        ),
        migrations.AddIndex(
            model_name='campocontrato',
            index=models.Index(fields=['contrato', 'orden'], name='contratos_c_contrat_0d95d4_idx'),
        ),
        migrations.AddIndex(
            model_name='firmantecontrato',
            index=models.Index(fields=['contrato', 'estado'], name='contratos_f_contrat_dd1c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='firmantecontrato',
            index=models.Index(fields=['token_acceso'], name='contratos_f_token_a_0eb9ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='firmantecontrato',
            unique_together={('contrato', 'email')},
        ),
        migrations.AddIndex(
            model_name='certificadofirma',
            index=models.Index(fields=['contrato', '-timestamp'], name='contratos_c_contrat_df7646_idx'),
        ),
        migrations.AddIndex(
            model_name='certificadofirma',
            index=models.Index(fields=['hash_certificado'], name='contratos_c_hash_ce_79ceea_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcontrato',
            index=models.Index(fields=['contrato', '-fecha_accion'], name='contratos_h_contrat_32fa22_idx'),
        ),
        migrations.AddIndex(
            model_name='historialcontrato',
            index=models.Index(fields=['tipo_accion', '-fecha_accion'], name='contratos_h_tipo_ac_cde5a2_idx'),
        ),
    ]
