# Generated by Django 5.1.2 on 2025-07-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversaciones', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google_maps', 'Google Maps'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('web', 'Sitio Web'), ('otro', 'Otro')], max_length=20)),
                ('tipo', models.CharField(choices=[('mensaje_directo', 'Mensaje Directo'), ('comentario_publico', 'Comentario Público'), ('respuesta', 'Respuesta'), ('nota_interna', 'Nota Interna')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_respuesta', models.BooleanField(default=False)),
                ('respuesta_automatica', models.BooleanField(default=False)),
                ('intencion_detectada', models.CharField(blank=True, choices=[('consulta', 'Consulta'), ('cotizacion', 'Cotización'), ('queja', 'Queja'), ('soporte', 'Soporte'), ('informacion', 'Información'), ('venta', 'Venta'), ('otro', 'Otro')], max_length=20, null=True)),
                ('sentimiento', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('neutro', 'Neutro'), ('negativo', 'Negativo')], max_length=10, null=True)),
                ('confianza_nlp', models.FloatField(blank=True, help_text='Confianza del análisis NLP (0-1)', null=True)),
                ('mensaje_original_id', models.CharField(blank=True, max_length=100, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('requiere_atencion', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='conversaciones.conversacion')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensajes',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['lead', 'fecha'], name='mensajes_lead_id_9b490d_idx'), models.Index(fields=['conversacion', 'fecha'], name='mensajes_convers_56aa6a_idx'), models.Index(fields=['tipo'], name='mensajes_tipo_4ade32_idx'), models.Index(fields=['es_respuesta'], name='mensajes_es_resp_915930_idx'), models.Index(fields=['requiere_atencion'], name='mensajes_requier_abf920_idx')],
            },
        ),
    ]
