# Generated by Django 5.1.2 on 2025-10-07 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('teams', '0002_team_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('CLOSED', 'Cerrada'), ('ARCHIVED', 'Archivada')], default='ACTIVE', max_length=20)),
                ('platform', models.CharField(blank=True, help_text='whatsapp, telegram, etc', max_length=50)),
                ('platform_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='leads.lead')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='teams.team')),
            ],
            options={
                'db_table': 'conversaciones',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Entrante'), ('OUTBOUND', 'Saliente')], max_length=10)),
                ('type', models.CharField(choices=[('TEXT', 'Texto'), ('IMAGE', 'Imagen'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento'), ('LOCATION', 'Ubicación')], default='TEXT', max_length=20)),
                ('content', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Datos adicionales del mensaje', null=True)),
                ('external_id', models.CharField(blank=True, help_text='ID del mensaje en la plataforma externa', max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversaciones.conversacion')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['sender_id', 'team'], name='conversacio_sender__5bbe47_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['team', 'status'], name='conversacio_team_id_e53a97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversacion',
            unique_together={('sender_id', 'team')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversacion', 'created_at'], name='conversacio_convers_f54833_idx'),
        ),
    ]
