# Generated by Django 5.1.2 on 2025-07-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversaciones', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['lead', 'estado'], name='conversacio_lead_id_399057_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_creacion'], name='conversacio_fecha_c_a1eb57_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['asignado_a'], name='conversacio_asignad_61b71f_idx'),
        ),
    ]
